### ISSUE TITLE
[QUESTION] - Repository blacklist

### ISSUE THREAD

**Issue by alexandresavicki** [SvanBoxel/organization-workflows#25]
There's a way to exclude a list of repositories to not run workflow?

I running workflow for an organization that's have some git ops repositories, this repositories are receiving push commits in to deffault branch at any time by some automation, so these repositories doesn't need run workflow.

I'm running my workflow with configuration bellow:

```
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
```
So i try to setup to run only on `pull_request` :

```
on:
  pull_request:
    branches: [ $default-branch ]
```
But doesn't work, it's still running for push events for any branch.

My main problem with this is that can exceed my Action runs quota easily.
