### ISSUE TITLE
Feature Request - Add an option to include too in organization-workflows-settings.yml

### ISSUE THREAD

**Issue by vikas027** [SvanBoxel/organization-workflows#37]
At the moment, at the time of installing the app, we can choose which repositories to choose and then optionally exclude them in `organization-workflows-settings.yml`.

It would be great if we can have an `include` (like below) option too in `organization-workflows-settings.yml` so that we can give the app full access to all repositories and then manage the `include` and `exclude` list from the `.github` repo itself.

```yaml
workflows_repository: our-organization-workflows
include_workflows_repository: false
include:
  repositories:
  - 'my-repo'
exclude:
  repositories:
  - '*'
```

This will help us to manage the central workflows using the git repository itself i.e. devs will not need access to the organization to make changes to the installed app.
