### ISSUE TITLE
Feature request: Make exclude possible for different checks

### ISSUE THREAD

**Issue by SVTOpenSource** [SvanBoxel/organization-workflows#40]
Currently, this action allows to run the checks using it on all, or a selected set of repositories. It allows exclusion of a set of repositories, with the config file: https://github.com/SvanBoxel/organization-workflows#app-configuration
However it does not allow for exclusion on a specific action level. 

Real life usage scenario would be:

I have two checks, lets say a markdown check and and a codeql check that I want to run organization-wide.
The markdown action should be run on all repos.
The codeql action on a set of repos.

Would it be possible to add this feature? Either so that it would be configured in the check it self, or letting organization-workflows-settings.yml handle multiple configuration blocks, tied to an action.yml maybe, I don't know about the best implementation.

**Comment by SvanBoxel** [comment]
The easiest way to do this today is by doing this check on a job level based on the payload event, and skip the job if it doesn't come from the repository you like to run this check on. 

Sample 

```
jobs:
  register-and-lint:
    if: ${{ github.event.client_payload.repository.name == <repo_name> }}
    runs-on: ubuntu-latest
    steps:
    - uses: SvanBoxel/organization-workflow@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: ${{ github.workflow }}
        enforce: true
        enforce_admin: true
        documentation: "README.md"
```

If you want to run this if statement for a list of repositories you can do something [like this](https://stackoverflow.com/a/70142531).
